# Analytics / Tracking / Ads
host,www.google-analytics.com,reject
host,strip.chat,reject
host,sessions.bugsnag.com,reject
host,notify.bugsnag.com,reject
host,api.mixpanel.com,reject
host,iadsdk.apple.com,reject
host,dit.whatsapp.net,reject
host,a.magsrv.com,reject
host,cdn.tsyndicate.com,reject
host,fbs.smoot.apple.com,reject
host,firebaselogging-pa.googleapis.com,reject
host,js.onclckbnr.com,reject
host,lf-leads-fe-scm.bytecdn.com,reject
host,log-hl.snssdk.com,reject
host,log0-misc-lf.amemv.com,reject
host,mssdk3-normal-hj.zijieapi.com,reject
host,ptelastaxo.com,reject
host,s10.histats.com,reject
host,sdk.51.la,reject
host,stats.g.doubleclick.net,reject
host,tnc0-aliec2.zijieapi.com,reject
host,www.googletagmanager.com,reject
host,go.mavrtracktor.com,reject
host,stats.g.doubleclick.com,reject
host,netapm.music.163.com,reject
host,clientlogsf.music.163.com,reject
host,clientlogdep.music.163.com,reject

# AdGuard
host,work.ua,reject
host,yummly.com,reject
host,woman.excite.co.jp,reject
host,minfin.com.ua,reject
host,auone.jp,reject
host,m.coupang.com,reject
host,ngoisao.vnexpress.net,reject
host,twowcan.com,reject
host,espncricinfo.com,reject
host,mathway.com,reject
host,clearnotebooks.com,reject
host,takagi-member.jp,reject