# ===================================================
# Rule Name:      Direct / Overseas Direct Rules
# Target Region:  Malaysia / Non-GFW Environments
# Policy:         Force DIRECT for all domains and IP-ASNs
# Services:       Apple / Google / Cloudflare / AWS / GitHub / Telegram / Facebook / WhatsApp
# ===================================================

# Apple
host-suffix,apple.com,direct
host-suffix,gstatic.com,direct
host-suffix,icloud-content.com,direct
host-suffix,cdn-apple.com,direct
host-suffix,gateway.icloud.com,direct
host-suffix,metrics.icloud.com,direct
host-suffix,mzstatic.com,direct
host-suffix,icloud.com,direct
host,mask-h2.icloud.com,direct
host,imap.mail.icloud.com.cn,direct
host,imap.mail.icloud.com,direct
ip-asn,714,direct

# Google
host-suffix,google.com,direct
host-suffix,google.com.my,direct
host-suffix,gmail.com,direct
host-suffix,googleusercontent.com,direct
ip-asn,15169,direct

# Cloudflare
host-suffix,cloudflare.com,direct
host-suffix,cloudflareinsights.com,direct
host-suffix,ocsp.digicert.com,direct
host-suffix,one.one.one.one,direct
ip-asn,13335,direct

# AWS
host-suffix,amazonaws.com,direct
ip-asn,16509,direct

# GitHub
host-suffix,github.com,direct
host-suffix,githubusercontent.com,direct
ip-asn,36459,direct
ip-asn,8075,direct

# Telegram
ip-asn,44907,direct
ip-asn,62014,direct
ip-asn,59930,direct
ip-asn,62041,direct
ip-asn,211157,direct

# Meta Services (Facebook & WhatsApp)
host-suffix,facebook.com,direct
host-suffix,fbcdn.net,direct
host-suffix,whatsapp.com,direct
host-suffix,whatsapp.net,direct
ip-asn,32934,direct

# TikTok
host-suffix,tiktok.com,direct
host-suffix,tiktokcdn.com,direct